# Generated by Django 3.2 on 2021-04-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='info_qr_code',
            field=models.ImageField(blank=True, upload_to='uploads/qr_codes'),
        ),
    ]
